Add Detekt reporter to checks.yml

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -4,7 +4,17 @@ jobs:
   Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     steps:
+
       - name: Check out repository code
         uses: actions/checkout@v2
+
       - name: Detekt Code Analysis 
-        run: ./gradlew detekt
+        run: ./gradlew detekt reportMerge --continue
+
+      # Make sure we always run this upload task, 
+      # because the previous step may fail if there are findings. 
+      - name: Upload SARIF to Github using the upload-sarif action 
+        uses: github/codeql-action/upload-sarif@v1 
+        if: success() || failure() 
+        with:
+          sarif_file: build/detekt/reports/merge.sarif
